version: "3.5"

services:
    app:
        deploy:
            resources:
                limits:
                    memory: 500M
        build:
            context: .
            dockerfile: Dockerfile
        restart: unless-stopped
        tty: true
        environment:
            SERVICE_NAME: backend
            SERVICE_TAGS: backend
        working_dir: /var/www/
        volumes:
            - ./:/var/www/html
            - ./:/var/www
        depends_on:
            - db
        ports:
            - "80:80"
            - "443:443"
        networks:
            - laravel
    adminer:
        image: adminer
        restart: always
        ports:
            - 8080:8080
        networks:
            - laravel
    db:
        image: mysql:5.7.22
        restart: always
        tty: true
        deploy:
            resources:
                limits:
                    memory: 350M
        environment:
            MYSQL_DATABASE: ${DB_DATABASE}
            MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
            MYSQL_PASSWORD: ${DB_PASSWORD}
            MYSQL_USER: ${DB_USERNAME}
        volumes:
            - ./docker/mysql/init.sql:/docker-entrypoint-initdb.d/init.sql:ro
            - ./.docker/mysql/dbdata:/var/lib/mysql:rw
        command: mysqld --init-file="/docker-entrypoint-initdb.d/init.sql"
        ports:
            - "3388:3306"
        healthcheck:
            test: "/usr/bin/mysql --user=root --password=root --execute \"SHOW DATABASES;\""
            interval: 2s
            timeout: 20s
            retries: 10
        networks:
            - laravel
networks:
    laravel:
        driver: bridge
